pbpk/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.contrib.auth.decorators import login_required

from pbpk import views

urlpatterns = patterns('',
    url(r'^$', views.WelcomePage, name='home'),
    url(r'^default', views.DefaultModel),
    #url(r'^oldModel', login_required(views.OldModels)),
    #url(r'^editDrug', login_required(views.EditDrug)),
    url(r'^editIntermediate', login_required(views.EditIntermediate)),
    url(r'^edit_model', login_required(views.Edit)),
    url(r'^NewModel', login_required(views.InitPage)),
    url(r'^DeleteModel', login_required(views.delete)),
    url(r'^userprofile', login_required(views.user_profile)),
    url(r'^tutorial_create', views.tutorial_create),
    url(r'^tutorial', views.tutorial),
    #url(r'^mpc_input?', views.MPCInput),
    #url(r'^results', views.MPCResults),

    # Authentication module
    url(r'^accounts/', include('allauth.urls')),

    # Administration page
    url(r'^admin/', include(admin.site.urls)),
    #url(r'^ajax_color_request/$', views.ajax_color_request),

    # api
    url(r'^get_plot_params/(?P<pk>\d+)/', views.get_plot_params),
    url(r'^get_step_params/(?P<pk>\d+)/', views.get_step_params),
)

pbpk/models.py
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
#
# Also note: You'll have to insert the output of 'django-admin.py sqlcustom [app_label]'
# into your database.
from __future__ import unicode_literals
from django.db.models.signals import post_save, m2m_changed
from django.db import models
from django.contrib.auth.models import User

def on_user_create(sender, instance, created, **kwargs):
    if created:
        d1 = Drug.objects.create(drug_name="default_drug", max_liver="1.4e-6", max_kidney="5.0e-6", max_influx= "0.04e-6", k_met="0.06", k_bile="0.0", k_kidney="0.0164",
                                                  p_skin="1.6", pi_skin="0.0095", p_kidney="0.14", pi_kidney="0.12", p_bladder="1.6", pi_bladder="0.0095",
                                                  p_liver="1.6", pi_liver="0.0095", p_rest="1.6", pi_rest="0.0095", pi_rbc="1.3", pi_plasma= "0.81",
                                                  p_lung="0.44", pi_lung="0.94")
        m1 = Models.objects.create(modelname="default", username=instance.username, bw="0.03", h="0.45", cardiac_output="16.5", skin_flow_factor = "0.058",skin_volume_fraction= "0.165", blood_skin_fraction="0.03",
                                          kidney_flow_factor="0.091", kidney_volume_fraction="0.017",blood_kidney_fraction="0.24",bladder_flow_factor="0.0033", bladder_volume_fraction= "0.0009",
                                          blood_bladder_fraction="0.03", blood_rest_fraction ="0.04", liver_flow_factor="0.162", liver_volume_fraction="0.055", blood_liver_fraction="0.31",
                                          blood_volume_fraction="0.5", lung_flow_factor="1.0", lung_volume_fraction="0.007", blood_lung_fraction="0.5", method="CloseLoop-MPC",
                                          method_params='{"N": 5, "intervals": 4, "step": 0.0833, "end": 4, "time": [0, 1, 2, 3 ], "setpoint": [4e-07, 4e-07, 4e-07, 4e-07], "time_int_final": [1, 2, 3, 4], "Q": 0.25, "R":5}')
        m1.drugs.add(d1)


class Drug(models.Model):
    id = models.AutoField(primary_key=True)
    drug_name = models.TextField(db_column='drugName', blank=False)  # Field name made lowercase.
    k_met = models.FloatField(blank=True, null=True, default=0.0)
    k_bile = models.FloatField(blank=True, null=True, default=0.0)
    k_kidney = models.FloatField(blank=True, null=True, default=0.0)
    max_liver = models.FloatField(blank=True, null=True, default=0.0)
    max_kidney = models.FloatField(blank=True, null=True, default=0.0)
    max_influx = models.FloatField(blank=True, null=True, default=0.0)
    p_skin = models.FloatField(db_column='P_skin', blank=True, null=True, default=0.0)  # Field name made lowercase.
    pi_skin = models.FloatField(db_column='Pi_skin', blank=True, null=True, default=0.0)  # Field name made lowercase.
    p_kidney = models.FloatField(db_column='P_kidney', blank=True, null=True, default=0.0)  # Field name made lowercase.
    pi_kidney = models.FloatField(db_column='Pi_kidney', blank=True, null=True, default=0.0)  # Field name made lowercase.
    p_bladder = models.FloatField(db_column='P_bladder', blank=True, null=True, default=0.0)  # Field name made lowercase.
    pi_bladder = models.FloatField(db_column='Pi_bladder', blank=True, null=True, default=0.0)  # Field name made lowercase.
    p_rest = models.FloatField(db_column='P_rest', blank=True, null=True, default=0.0)  # Field name made lowercase.
    pi_rest = models.FloatField(db_column='Pi_rest', blank=True, null=True, default=0.0)  # Field name made lowercase.
    p_liver = models.FloatField(db_column='P_liver', blank=True, null=True, default=0.0)  # Field name made lowercase.
    pi_liver = models.FloatField(db_column='Pi_liver', blank=True, null=True, default=0.0)  # Field name made lowercase.
    pi_rbc = models.FloatField(db_column='Pi_rbc', blank=True, null=True, default=0.0)  # Field name made lowercase.
    pi_plasma = models.FloatField(db_column='Pi_plasma', blank=True, null=True, default=0.0)  # Field name made lowercase.
    p_lung = models.FloatField(db_column='P_lung', blank=True, null=True, default=0.0)  # Field name made lowercase.
    pi_lung = models.FloatField(db_column='Pi_lung', blank=True, null=True, default=0.0)  # Field name made lowercase.
    min_liver = models.FloatField(blank=True, null=True, default=0.0)
    min_kidney = models.FloatField(blank=True, null=True, default=0.0)
    max_residual = models.FloatField(blank=True, null=True, default=1)
    min_residual = models.FloatField(blank=True, null=True, default=0.0)
    max_skin = models.FloatField(blank=True, null=True, default=1)
    min_skin = models.FloatField(blank=True, null=True, default=0.0)
    max_bladder = models.FloatField(blank=True, null=True, default=1)
    min_bladder = models.FloatField(blank=True, null=True, default=0.0)
    max_lung = models.FloatField(blank=True, null=True, default=1)
    min_lung = models.FloatField(blank=True, null=True, default=0.0)
    p_organ1 = models.FloatField(db_column='P_organ1', blank=True, null=True, default=0.0)  # Field name made lowercase.
    pi_organ1 = models.FloatField(db_column='Pi_organ1', blank=True, null=True, default=0.0)  # Field name made lowercase.
    p_organ2 = models.FloatField(db_column='P_organ2', blank=True, null=True, default=0.0)  # Field name made lowercase.
    pi_organ2 = models.FloatField(db_column='Pi_organ2', blank=True, null=True, default=0.0)  # Field name made lowercase.
    p_organ3 = models.FloatField(db_column='P_organ3', blank=True, null=True, default=0.0)  # Field name made lowercase.
    pi_organ3 = models.FloatField(db_column='Pi_organ3', blank=True, null=True, default=0.0)  # Field name made lowercase.
    p_organ4 = models.FloatField(db_column='P_organ4', blank=True, null=True, default=0.0)  # Field name made lowercase.
    pi_organ4 = models.FloatField(db_column='Pi_organ4', blank=True, null=True, default=0.0)  # Field name made lowercase.
    p_organ5 = models.FloatField(db_column='P_organ5', blank=True, null=True, default=0.0)  # Field name made lowercase.
    pi_organ5 = models.FloatField(db_column='Pi_organ5', blank=True, null=True, default=0.0)  # Field name made lowercase.
    p_heart = models.FloatField(db_column='P_heart', blank=True, null=True, default=0.0)  # Field name made lowercase.
    pi_heart = models.FloatField(db_column='Pi_heart', blank=True, null=True, default=0.0)  # Field name made lowercase.
    max_heart = models.FloatField(blank=True, null=True, default=1)
    min_heart = models.FloatField(blank=True, null=True, default=0.0)
    p_muscle = models.FloatField(db_column='P_muscle', blank=True, null=True, default=0.0)  # Field name made lowercase.
    pi_muscle = models.FloatField(db_column='Pi_muscle', blank=True, null=True, default=0.0)  # Field name made lowercase.
    max_muscle = models.FloatField(blank=True, null=True, default=1)
    min_muscle = models.FloatField(blank=True, null=True, default=0.0)
    p_spleen = models.FloatField(db_column='P_spleen', blank=True, null=True, default=0.0)  # Field name made lowercase.
    pi_spleen = models.FloatField(db_column='Pi_spleen', blank=True, null=True, default=0.0)  # Field name made lowercase.
    max_spleen = models.FloatField(blank=True, null=True, default=1)
    min_spleen = models.FloatField(blank=True, null=True, default=0.0)
    p_placental = models.FloatField(db_column='P_placental', blank=True, null=True, default=0.0)  # Field name made lowercase.
    pi_placental = models.FloatField(db_column='Pi_placental', blank=True, null=True, default=0.0)  # Field name made lowercase.
    max_placental = models.FloatField(blank=True, null=True, default=1)
    min_placental = models.FloatField(blank=True, null=True, default=0.0)

    organ1_params = models.TextField(blank=True, null=True, max_length=2048)  # json string with method parameters for additional organs

    class Meta:
        db_table = 'drugs'


class Models(models.Model):
    id = models.AutoField(primary_key=True)
    username = models.TextField(db_column='userName', blank=False)  # Field name made lowercase.
    modelname = models.TextField(db_column='modelName', blank=False,  error_messages={'unique':"This modelname has already been registered."})  # Field name made lowercase.

    bw = models.FloatField(blank=True, null=True)
    h = models.FloatField(blank=True, null=True)
    cardiac_output = models.FloatField(blank=True, null=True, default=0.0,)
    skin_flow_factor = models.FloatField(blank=True, null=True, default=0.0)
    skin_volume_fraction = models.FloatField(blank=True, null=True, default=0.0)
    blood_skin_fraction = models.FloatField(blank=True, null=True, default=0.0)
    kidney_flow_factor = models.FloatField(blank=True, null=True, default=0.0)
    kidney_volume_fraction = models.FloatField(blank=True, null=True, default=0.0)
    blood_kidney_fraction = models.FloatField(blank=True, null=True, default=0.0)
    bladder_flow_factor = models.FloatField(blank=True, null=True, default=0.0)
    bladder_volume_fraction = models.FloatField(blank=True, null=True, default=0.0)
    blood_bladder_fraction = models.FloatField(blank=True, null=True, default=0.0)
    blood_rest_fraction = models.FloatField(blank=True, null=True, default=0.0)
    liver_flow_factor = models.FloatField(blank=True, null=True, default=0.0)
    liver_volume_fraction = models.FloatField(blank=True, null=True, default=0.0)
    blood_liver_fraction = models.FloatField(blank=True, null=True, default=0.0)

pbpk/forms.py
from django.contrib.auth.models import User
from django import forms
from pbpk.models import Models, Drug



class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ('username', 'email', 'password')

class DrugForm(forms.ModelForm):
    class Meta:
        model=Drug
        exclude = ('drugname',)
        widgets = {
            'drugname': forms.TextInput,
        }

class ModelForm(forms.ModelForm):

    class Meta:
        model = Models
        exclude = ('username','drugs',)
        error_css_class = 'error'


        widgets = {
            'username': forms.TextInput,
            'modelname': forms.TextInput,
        }

    def clean(self):
        cleaned_data = super(ModelForm, self).clean()
        blood_volume_fraction = cleaned_data.get("blood_volume_fraction")
        lung_flow_factor = cleaned_data.get("lung_flow_factor")
        lung_volume_fraction= cleaned_data.get("lung_volume_fraction")
        blood_lung_fraction = cleaned_data.get("blood_lung_fraction")

        if blood_volume_fraction and lung_flow_factor and lung_volume_fraction and blood_lung_fraction:
            # Only do something if both fields are valid so far.
            if ((blood_volume_fraction == "0.0") & ((lung_flow_factor=="0.0") | (lung_volume_fraction=="0.0") | (blood_lung_fraction == "0.0") )) :

                raise forms.ValidationError("Cannot be created model without blood and lung.")
            elif (blood_volume_fraction == "0.0") :
                msg="Cannot be created model without blood!!"
                self.add_error(None, msg)
                raise forms.ValidationError("Cannot be created model without blood.")
        return cleaned_data

pbpk/templates/base.html
<!DOCTYPE html>

<html>
	<head>
		<title>PBPK Model</title>
        <meta charset="utf-8" />

        <script src="/static/js/jquery-1.11.0.min.js"></script>
	    <script src="/static/js/flat-ui.min.js"></script>
        <script src="/static/js/lightbox.min.js"></script>
        <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
        <script src="/static/js/jQuery.print.js"></script>

        <script type="text/javascript" src="/static/js/additional_organs.js"></script>
        <script type="text/javascript" src="/static/js/mpc.js"></script>
        <script src="/static/js/trip.min.js"></script>

        <link rel="stylesheet" href="/static/css/bootstrap.min.css" media="all">
        <link rel="stylesheet" href="/static/css/flat-ui.min.css" media="all">
        <link rel="stylesheet" href="/static/css/style.css">
        <link href="/static/css/lightbox.css" rel="stylesheet" />
        <link rel="stylesheet" type="text/css" href="/static/css/trip.min.css" />


        {% block header %}
        {% endblock %}
        <!--<link rel="stylesheet" href="/static/css/main.css" media="all">-->
        <script>
          (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
          (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
          m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
          })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

          ga('create', 'UA-67994660-1', 'auto');
          ga('send', 'pageview');

        </script>
	</head>

	<body>
        {% include "util/menu.html" %}

        <div class="wrapper">
		    {% block content %}
		    {% endblock %}
        </div>

	</body>

</html>

pbpk/templates/delete.html
{% extends "base.html"%}

{% block content %}

<div>
	<h1>The selected model has been deleted</h1>
</div>

{% endblock %}

pbpk/templates/delete_drug.html
{% extends "base.html"%}

{% block content %}

<div>
	<h1>The selected drug has been deleted</h1>
</div>

{% endblock %}

pbpk/templates/delete_model.html
{% extends "base.html"%}

{% block content %}
<form method="post"> {% csrf_token %}

{% if form.errors %}
    <p class="error">{{form.errors}}</p>
{% endif %}

	<div class="div-form-table" style=" width: 40%;"><b>Please select the model you want to delete:</b><br><br>
	<table class="form-table">
		<tr>

			<td>
				<b>Modelname:</b>
                {{select_model}}
			</td>
            <td>
				<b>Drugname:</b>
                {{select_drug}}
			</td>

            <!--<td>
                <input type="button" id="New_drug" value="New_drug">
            </td>-->


		</tr>
	</table>
    </div>
    <br>
	<div style="color : red">{{error}}</div><br>
	<input type="submit" value="Delete this model" class="btn btn-red btn-block btn-lg btn-primary" style="width: 10%; border: 2px solid #2f4154;">

	<!-- <div id="divCheckbox" style="visibility: hidden; display:inline;">Here are the results!</div>-->
</form>

<script>
    function get_drug(){
        $.ajax({
            url: '/DeleteModel/',
            type: 'POST',
            data: {
                'modelname': $('#id_modelname').val(),
                'csrfmiddlewaretoken': '{{csrf_token}}'
            },

            success: function(drugs, textStatus, jqXHR) {
                var e = $('#id_drugname');
                e.empty();
                for (var i=0; i<drugs.length; i++) {
                    drug = drugs[i];
                    e.append($('<option>', { value : drug[0] }).text(drug[1]));
                }
            }
        });
    }
</script>
{% endblock %}

pbpk/templates/edit_drug.html
{% extends "base.html"%}
{% block content %}
<form method="post"> {% csrf_token %}

{% if form.errors %}
    <p class="error">{{form.errors}}</p>
{% endif %}

	<div class="div-form-table" style=" width: 40%;"><b>Please select the model you want to edit:</b><br><br>
	<table class="form-table">
		<tr>
            <td>
				<b>Modelname:</b>
				<!--<input type="text" id="modelname" name="modelname" value="{{modelname}}" class="form-control"/>-->
                {{select_model}}
			</td>
			<td>
				<b>Drugname:</b>
				<!--<input type="text" id="modelname" name="modelname" value="{{modelname}}" class="form-control"/>-->
                {{select_drug}}
			</td>

		</tr>
	</table>
    </div>

	<div style="color : red">{{error}}</div><br>
	<input type="submit" value="Edit this model" class="btn btn-block btn-lg btn-primary" style="width: 10%; border: 2px solid #2f4154;">

	<!-- <div id="divCheckbox" style="visibility: hidden; display:inline;">Here are the results!</div>-->
</form>
{% endblock %}


<script>
function get_drug(){
    new Ajax.Request('/auto/ajax_purpose_staff/', {
    method: 'post',
    parameters: $H({'type':$('id_type').getValue()}),
    onSuccess: function(transport) {
        var e = $('id_color')
        if(transport.responseText)
            e.update(transport.responseText)
    }
    }); // end new Ajax.Request
}

</script>

pbpk/templates/edit_intermediate.html
{% extends "base.html"%}

{% block content %}
<form method="post"> {% csrf_token %}

{% if form.errors %}
    <p class="error">{{form.errors}}</p>
{% endif %}

	<div class="div-form-table" style=" width: 40%;"><b>Please select the model you want to edit:</b><br><br>
	<table class="form-table">
		<tr>

			<td>
				<b>Modelname:</b>
				<!--<input type="text" id="modelname" name="modelname" value="{{modelname}}" class="form-control"/>-->
                {{select_model}}
			</td>
            <td>
				<b>Drugname:</b>
				<!--<input type="text" id="modelname" name="modelname" value="{{modelname}}" class="form-control"/>-->
                {{select_drug}}
			</td>

            <!--<td>
                <input type="button" id="New_drug" value="New_drug">
            </td>-->


		</tr>
	</table>
    </div>
    <br>
	<div style="color : red">{{error}}</div><br>
	<input type="submit" value="Edit this model" id="edit_model" class="btn btn-block btn-lg btn-primary" style="width: 10%; border: 2px solid #2f4154;width: 10%; display:none; ">

	<!-- <div id="divCheckbox" style="visibility: hidden; display:inline;">Here are the results!</div>-->
</form>

<script>
    function get_drug(){
        $.ajax({
            url: '/editIntermediate/',
            type: 'POST',
            data: {
                'modelname': $('#id_modelname').val(),
                'csrfmiddlewaretoken': '{{csrf_token}}'
            },

            success: function(drugs, textStatus, jqXHR) {
                var e = $('#id_drugname');
                e.empty();
                for (var i=0; i<drugs.length; i++) {
                    drug = drugs[i];
                    e.append($('<option>', { value : drug[0] }).text(drug[1]));
                }
            }
        });
    }


$('#id_modelname').one('change', function() {
     //$('#edit_model').prop('disabled', false);
     $('#edit_model').show();
});

</script>
{% endblock %}

pbpk/templates/init.html
<!DOCTYPE html>

<html>
	<head>
		<title>PBPK Model</title>
	</head>

	<body style:"margin: 0">
		<h1 style="background-color: #ddd; color: #888; margin: 0 height: 50px">
			PBPK Modelling for DMA
		</h1>
		{% block content %}
		{% endblock %}
	</body>
</html>

pbpk/templates/mainPage.html
{% extends "base.html" %}

{% block content %}

<div style="width: 90%; margin: 0px auto;margin-left: auto ;margin-right: auto ;">
<h2 class="text-center">Welcome!</h2>
<div class="info text-center" >This is a web application for creating and simulating PBPK models and for computing optimal drug administrations using Model Predictive Control.
    The development of this application was funded by project 11ΣYN_10_1152, which was co-financed by the European Union and Greece,Operational Programme “Competitiveness & Entrepreneurship”,
    NSFR 2007–2013 in the context of GSRT-National action “Cooperation”. <br><br>
</div>
<div style="display: none">
	<table>
			<tr>
				<td><a href="/NewModel">Create a New Model</a></td>
			</tr>
			<tr>
				<td><a href="/oldIntermediate">Use a pre-extisted Model</a></td>
			</tr>
			<tr>
				<td><a href="/editIntermediate">Edit and use a pre-existed Model</a></td>
			</tr>
			<tr>
				<td><a href="/default">Use the Default Model</a></td>
			</tr>
		</table>
</div>

<div class="row demo-tiles">
        <div class="col-xs-3 initial" style="left:30%; position:relative;">
          <div class="tile">
            <img src="/static/img/check.png" alt="Compas" class="tile-image big-illustration">
            <p>Use Default model.</p>
            <a class="btn btn-primary btn-large btn-block" href="/default">Default model</a>
          </div>
        </div>

        <div class="col-xs-3 initial" style="left:30%; position:relative;">
          <div class="tile">
            <img src="/static/img/compose.png" alt="Infinity-Loop" class="tile-image">
            <p>Create new Model.</p>
            <a class="btn btn-primary btn-large btn-block" href="/NewModel">Create model </a>
          </div>
        </div>

        <div class="col-xs-3 initial" style="left:30%; position:relative;">
          <div class="tile">
            <img src="/static/img/barchart.png" alt="Pensils" class="tile-image">
            <p>Modify Existing Model. </p>
            <a class="btn btn-primary btn-large btn-block" href="/editIntermediate">Modify model</a>
          </div>
        </div>

 </div>
 {% if not user.is_authenticated %}
 <div class="row demo-tiles">
        <div class="col-xs-3 initial2" style="left:30.5%; position:relative;">
          <div class="tile">
            <img src="/static/img/pencils.svg" alt="Compas" class="tile-image big-illustration">
            <h3 class="tile-title">Already have account?</h3>
            <p></p>
            <a class="btn btn-primary btn-large btn-block" href="/accounts/login/">Login</a>
          </div>
        </div>

        <div class="col-xs-3 initial2" style="left:30.5%; position:relative;">
          <div class="tile">
            <img src="/static/img/retina.svg" alt="Infinity-Loop" class="tile-image">
            <h3 class="tile-title">Create new account</h3>
            <p></p>
            <a class="btn btn-primary btn-large btn-block" href="/accounts/signup">Create account </a>
          </div>
        </div>
</div>
</div>
{% endif %}
 <div class="push"></div>

<footer id="footer" class="footer" style="background-color:#2c3e50;">
    <p class="center"><img src="/static/img/espalogo.png" alt="Pensils" class="tile-image text-center"></p>
    <div class="text-center">Copyright © 2015 .All rights reserved.</div>
</footer>
{% endblock %}

pbpk/templates/user_profile.html
{% extends "base.html"%}

{% block content %}
<div>
    <img src="/static/img/profle.png" alt="Welcome to Mail App" style="float:left;">
    <h1 style="padding-left : 30px;float:left;">{{user.username}}</h1>

</div>
<div style="margin-top: 10%; ">
<div class="panel panel-default" style="float:left; width: 20%; ">
    <div class="panel-heading" style="background-color: #1ABC9C;">
        <h3 class="panel-title">{{user.username}}'s models</h3>
    </div>
    <div class="panel-body">
        <ul>
        {% for model in models %}
            <li>{{model.modelname}}</li>
        {% empty %}
            <p> You have not created any model yet!</p>
        {% endfor %}
        </ul>
    </div>
</div>
<div class="panel panel-default" style="float:left; width: 20%; margin-left:5px; ">
    <div class="panel-heading" style="background-color: #1ABC9C;">
        <h3 class="panel-title">{{user.username}}'s drugs</h3>
    </div>
    <div class="panel-body">
        <ul>
        {% for drug in drugs %}
            <li>{{drug.drug_name}}</li>
        {% empty %}
            <h6>You have not created any drug yet!</h6>
        {% endfor %}
        </ul>
    </div>
</div>
</div>
{% endblock %}